# Generated by Django 5.0.3 on 2024-05-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_wishlistitem_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='image_id',
        ),
    ]
